language: 'node_js'
node_js:
  - 'node'
services: 
  - 'postgresql'
before_install:
  # - psql -c 'create database postgres;' -U postgres
before_script:
  - npm install -g bower
  - bower install
  - export COVEYENV=DEV
  - node server/server.js &
  - sleep 7
  - jobs
  - kill %1
  - sleep 2
script:
  - gulp karma
  - gulp mocha