language: 'node_js'
node_js:
  - 'node'
services: 
  - 'postgresql'
before_install:
  # - psql -c 'create database postgres;' -U postgres
before_script:
  - npm install -g bower
  - bower install
  # - node server/server.js &